[package]
name = "rust_ffi_test"
version = "0.1.0"
authors = ["sadnessOjisan <sadness.ojisan@gmail.com>"]
edition = "2021"
links = "test"
build = "build.rs"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[dependencies]
libc = "0.2"